name: Build ESP-IDF Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Create venv
        run: |
          python3.8 -m venv esp-idf-venv
          echo "$PWD/esp-idf-venv/bin" >> $GITHUB_PATH

      - name: Build with ESP-IDF v4.1
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v4.1
          target: esp32
          path: '.'

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            build/*.bin
            build/*.elf
            build/bootloader/bootloader.bin
            build/partition_table/partition-table.bin
